### PR TITLE
Add issue templates for features, bugs, releases

### PR DESCRIPTION
**Pull request by meghanrjones**
Fixes https://github.com/GenericMappingTools/dcw-gmt/issues/23

### CODE REVIEW

**Review by PaulWessel — APPROVED** [review]
Did we want to add the check item for updating oceania?  I have not written that script yet.

**Comment by meghanrjones** [comment]
> Did we want to add the check item for updating oceania? I have not written that script yet.

Yes, I think so. Would this be a separate script or go into the Makefile similar to the ftp steps?

**Comment by PaulWessel** [comment]
I am writing something now.  I think it should get the tar ball from the official size, scp to the server, expand in the geography directory, them cp all files from the directory-version up to the parent dir, then remove the empty directory and the tarball, etc.

**Comment by PaulWessel** [comment]
It will be triggered by `make update-dataserver`.

**Pull request merged**
