### PR TITLE
Fix ru.txt

### LINKED ISSUE #33: Error in Russia.
Some islands of RU.ARK (in red@50) are not included in RU (in blue@50). 

I already have the new RU.txt. Later I will make the PR. This new PR should be dcw 2.0.2? 
Also, there is an smaller bug in the coast. Tomorrow I will try to fix it. 

`gmt coast -RRU.ARK -W -Df -png Rusia -B -JQ15c -ERU.ARK+gred@50 -ERU+gblue@50`

Rusia

### PR DESCRIPTION
**Pull request by Esteban82**
Close #33.

Paul, please check that the file is correct. I think so but I am not completely sure. Is it the same if the data is separated by tab or spaces?

### CODE REVIEW

**Review by PaulWessel — APPROVED** [review]
It is best to use tabs for space reasons.  If you look at the RU.txt now it has this format

`         93.228172         81.074379`

and that adds 18 spaces and that almost doubles the size of one record, then times N a large integer.  So please by a single tab between lon lat and remove the leading spaces.  None of this matters for the reading and it is not files we distribute, but we might as well keep the repo as small as we can :-)

**Comment by Esteban82** [comment]
Ok. I see. The records that I add have tabs but I replaced it with spaces following the previous records. And the file increase in 2 Mb.

**Comment by Esteban82** [comment]
> now it has this format
> 
> ` 93.228172 81.074379`

So the format should be `longValue whitespace latValue`? Without any whitespace/tab at the beginning? 

Also, can I Squash and merge, right?

**Comment by joa-quim** [comment]
And you don't need more than 5 decimals.

**Comment by Esteban82** [comment]
> True, but we have stuck with 6 decimal.

Any suggestion on how to do this? `printf`? gmt convert?

**Comment by PaulWessel** [comment]
I think I have used gmt convert for this in the past, with

`gmt convert old.file -fg --FORMAT_GEO_OUT=-D --FORMAT_FLOAT_OUT=%.6lf > new.file`

If we want 0-360 then use +D

**Comment by Esteban82** [comment]
I think that the format is now ready. Let me know so I can make a PR with all the other files.

**Comment by PaulWessel** [comment]
OK, I have approved this one already so you can squash and merge.

**Pull request merged**
