### PR TITLE
Finalize prep for 2.1.0

### PR DESCRIPTION
**Pull request by PaulWessel**
Forgot to update Makefile.  Also add release entry in ChangeLog.  Once merged we will build and release.

### CODE REVIEW

**Review by Esteban82 — APPROVED** [review]
Should we include a description of the source of the bounding box and lists?

**Comment by PaulWessel** [comment]
OK, maybe you can make an entry in README.me for that on this branch?

**Comment by Esteban82** [comment]
> OK, maybe you can make an entry in README.me for that on this branch?

I am going to sleep. Maybe tomorrow. If you prefer, go ahead with this.

**Comment by PaulWessel** [comment]
I will try.

**Comment by PaulWessel** [comment]
Please check this commit, @Esteban82 and fixed my URLs if they are wrong, as well as anything else that is wrong!
Feel free to add 1-2 more example of usage as well.

**Comment by joa-quim** [comment]
Sorry Federico, I should have tried this already. I run this Julia script to round the limits to more pleasant numbers
```
fid = open("dcw-collections_round.txt", "w")
open("dcw-collections.txt") do f
	for l in eachline(f)
		if startswith(l, "region")
			bb = parse.(Float64, split(split(l)[2], "/"))
			bb = GMT.round_wesn([bb[1] bb[2] bb[3] bb[4]])
			s = @sprintf("region: %.12g/%.12g/%.12g/%.12g/", bb[1], bb[2], bb[3], bb[4])
			println(fid, s)
		else
			println(fid, l)
		end
	end
end
close(fid)
```
Maybe you can try it to see if some of those tight limits are a bit better now.
[dcw-collections_round.zip](https://github.com/GenericMappingTools/dcw-gmt/files/7833546/dcw-collections_round.zip)
.

**Comment by Esteban82** [comment]
I will try. Now I am having a problem. I have 2.0.1 installed (in local/share/). I deleted it  so GMT will download the new version  but I am getting this error:

```
gmt --show-dcw
gmt [NOTICE]: Downloading dcw-gmt.nc for the first time - be patient
gmt [ERROR]: Libcurl Error: HTTP response code said error
gmt [WARNING]: You can turn remote file download off by setting GMT_DATA_UPDATE_INTERVAL to "off"
unknown

```

**Comment by Esteban82** [comment]
> [dcw-collections_round.zip](https://github.com/GenericMappingTools/dcw-gmt/files/7833546/dcw-collections_round.zip)

However, I checked the file. All the regions have an extra  "/" at the end. 
I agree that we should limit the numbers. But, too many? I see that there most of them have no  decimals or just 1. 

```
tag: SAM South America
region: -82/-34/-56/14/
tag: AFR Africa
region: -18/52/-36/38/
tag: ASI Asia
region: 24/192/-12/82/

```

**Comment by PaulWessel** [comment]
Does it matter with the decimals? Users aren’t typing those

**Comment by Esteban82** [comment]
I think we should have 6 decimales (as the dcw polygons).

**Comment by joa-quim** [comment]
Sorry, I’ll fiz that later.
The issue is not the number of decimals. The issue is that many zones were too tight and my “my” rounding rounds to the next decade or so. It’s a clever rounding. Not just dropping some figures.

**Comment by joa-quim** [comment]
Here it goes without the trailing slash

[dcw-collections_round.zip](https://github.com/GenericMappingTools/dcw-gmt/files/7834249/dcw-collections_round.zip)

**Comment by Esteban82** [comment]
> The issue is not the number of decimals. The issue is that many zones were too tight and my “my” rounding rounds to the next decade or so. It’s a clever rounding. Not just dropping some figures.

I try it. It looks fine. But, what would the difference with -Rcode+e/r/R? I think the users should have the option to have the exact bounding box.
It is not possible to add the formula for the clever rounding as a modifiers for -R (-RIHO28+c)?

**Comment by PaulWessel** [comment]
Sorry if I misunderstood, but I thought @joa-quim found some cases where the exact limits clipped features in **coast**? Otherwise I agree with @Esteban82 that we want tight BB here; that is why there is **+r** and **+R**, no?

**Comment by joa-quim** [comment]
Yes, Iberia was one of them and, if not mistaken, Andes was another.
And sorry but I don't understand the concept of a tight bounding box for regions that themselves have fuzzy limits.

**Comment by Esteban82** [comment]
Only the 37 areas from Natural Earth have fuzzy limits. Those yes can and should revised. I will check later only for those areas. 

The other regions have a precise limit (islands, lakes, etc). The same for seas and oceans (which follow the IHO convetion).

**Comment by joa-quim** [comment]
OK, let's see the _North Sea_ for example.
```
tag: IHO4 North Sea
region: -4.444193999999925/9.835806000000048/50.93373021900004/61.02791700000006
```
vs
```
tag: IHO4 North Sea
region: -4.8/10/50.8/61.2
```
Do you believe the limits of the North Sea are accurately defined up to 10 cm (6 decimal places)? Off course if someone digitized a map the polygon will have a lot of decimals. Do we want that by default a map has ugly limits instead of a nicer ones, even if it slightly overflows? But I won't insist on this anymore.

**Comment by PaulWessel** [comment]
No, certainly not accurate to those decimals.  But you changed -4.444 to -4.8 which is several km.

**Comment by joa-quim** [comment]
Yes, it increased the NS width by ~2%
```
((10 + 4.8) / (9.835806000000048 + 4.444193999999925) -1) * cosd(57)
0.0198
```

**Comment by PaulWessel** [comment]
Would seem it would be better with things like

`region: -4.44/9.84/50.93/61.03`

which does not change it too much but still eliminates lots of decimals.  Of course, I do not really care about the final values and we do not have to take this IHO literally, but since there are things the users won't really see or enter, perhaps some sensible rounding is OK but not changing things by several percent?

**Comment by joa-quim** [comment]
And here we are back to the beginning. This was never about the number of decimals but instead to have nicer limits. Like we do with **-Ba**

**Comment by Esteban82** [comment]
> Do you believe the limits of the North Sea are accurately defined up to 10 cm (6 decimal places)? Off course if someone digitized a map the polygon will have a lot of decimals. Do we want that by default a map has ugly limits instead of a nicer ones, even if it slightly overflows?

In the case of seas and oceans, I took the shp file from this paper: ["A New Digital Map of Limits of Oceans and Seas Consistent with High-Resolution Global Shorelines](https://meridian.allenpress.com/jcr/article-abstract/29/2/471/144617/A-New-Digital-Map-of-Limits-of-Oceans-and-Seas?redirectedFrom=fulltext)" and it says: "Positioning precision of reference points is approximately 10 s of meridian arc (about 300 m)." 10 s = 0.00277 degrees of arc.  So I think we could use 3/4 decimals for the seas and oceans.

**Comment by Esteban82** [comment]
> And here we are back to the beginning. This was never about the number of decimals but instead to have nicer limits. Like we do with **-Ba**

But I think is someone wants a nicer limits, then the modifiers should be used -Rcode+e/r/R. 

I think we should stick to the exact limit because it is consistent with the use of the dcw-countries for the region (e.g. -RIT) where the user gets the exact limit.

**Comment by PaulWessel** [comment]
How about we use fewer decimals for the natural Earth regions as per @joa-quim list but stick with 4 decimals where things are provided with higher-quality data.  The decision to pad and round is up to the user via the modifiers and should not be done irrevocably by us.

**Comment by joa-quim** [comment]
> the exact limit 

There is no exact limit of a Sea or Ocean. But I said I would shut up and didn't. Sorry.

**Comment by Esteban82** [comment]
> There is no exact limit of a Sea or Ocean.

Naturally it doesn't. But we are following the "Limits of Oceans and Seas" of IHO53 which by convention define straight lines that separates the different seas and oceans.

**Comment by Esteban82** [comment]
These are the regions from Natural Earth using Joaquim's file:
[Geography_relief.pdf](https://github.com/GenericMappingTools/dcw-gmt/files/7842058/Geography_relief.pdf)

**Comment by PaulWessel** [comment]
> But I said I would shut up and didn't. Sorry.

Not an easy thing to do for you, so instantly forgiven. :-)

**Comment by PaulWessel** [comment]
Perhaps this is exactly what @joa-quim mention earlier but when I look at the Andes Mountains in the latest PDF my gut reaction is that if I needed to make a map of the Andes I would certainly not chop off the tiny part of Peru and Equador as that looks odd, no?  I understand the Andres is not cropped but still...

**Comment by Esteban82** [comment]
Yes, I think that for the regions from Malay Archipelago onwards we could use Joaquims bounding box region. For the previous regions (continents, and micro/mela/polynesia) I personally edited the values to fit the GSHHG.

**Comment by Esteban82** [comment]
What do you think of the Eastern limit of Europe? Is it ok? Or should I extend it up to the Urals?

**Comment by PaulWessel** [comment]
I think for this purpose it may be better to a bit further east.  The actual "Europe" limit is not a single longitude of course, but I think it would help to be able to see the Urals or part of them, whatever looks OK with you.

**Comment by PaulWessel** [comment]
Are you happy with the entry in README.md now, @Esteban82 ? I can then merge this in.  We then await the changes etc regarding daw-collections.txt in the other branch.

**Comment by Esteban82** [comment]
> Are you happy with the entry in README.md now, @Esteban82 ?

I modified it some days ago. I don't know if you see it. Check it, specially for any typo or grammar error.

**Comment by PaulWessel** [comment]
Yep, should have told you had had a look.  Thanks.  OK so I think I will merge this.

**Pull request merged**
