### PR TITLE
dcw-collections.txt: fix typo

### PR DESCRIPTION
**Pull request by anbj**

### CODE REVIEW

**Comment by PaulWessel** [comment]
FYI, also please add an entry to the ChangeLog the next time you fix an issue like that - this avoids having to do a separate PR later and I forgot to add it to yours before merging :-)

**Comment by anbj** [comment]
Will do, Paul. Thanks.

**Comment by anbj** [comment]
How often is this synced with what is downloaded through gmt?
I just noticed that running the scripts here (https://github.com/GenericMappingTools/dcw-gmt/pull/31#issuecomment-1015719780), generates a map of *Skaggerak*, but in *dcw-collections.txt* it's written correctly (Skagerrak)

**Comment by PaulWessel** [comment]
If you are using DCW via the gmt server then there is not yet any mechanism to refresh the files you get if they change in the server.  If you delete the ./gmt/geography/dcw folder then it will force a redownload.  But the server only has the latest official version (2.1.0 now) so any changes in master will require you to build your own dcw file from source and use that locally.

**Comment by anbj** [comment]
Thanks. My workflow involves downloading the tarball manually when setting up gmt.

Another question, 
* will ``dcw-collections.txt`` always be downloaded from the gmt server if it is missing, and placed in ``~/.gmt/geography/dcw``? * Any checksums involved here? I can see cases where I would want to add custom codes in my ``dcw-collections.txt`` (as an 'init system'-script) before setting up gmt  - will this file be overwritten when I compile/install gmt? 
* If I download the dcw tar ball manually, will ``dcw-collections.txt`` be copied from the extracted files rather than downloaded from the server during compilation/installation?

**Comment by anbj** [comment]
Thanks Esteban. My thought was; it's likely that I will include my own codes when I set up a new system. This involves creating ``.gmt/dcw/geography/dcw-collections.txt`` with content, *before* gmt and dcw is installed. Will then ``dcw-collections.txt`` be overwritten? Or since it already exists, nothing will be cone? In case I will be missing all the *default* codes, that comes included in the distribution.

**Comment by Esteban82** [comment]
See the first comment of Paul here (https://github.com/GenericMappingTools/gmt/pull/6064#issue-1064888386). 

I try it but without any luck. Maybe it wasn't implement yet? Pinging @PaulWessel.

**Comment by Esteban82** [comment]
BTW, Do you have any suggestion to add in the official distribution?

**Comment by anbj** [comment]
In one way, not really. You've done a brilliant job, and this will be super useful to many users, including me.

That said (as a geologist), one could imagine also including entries for

* tectonic plates
* oceanic features such as (see e.g. https://www.gebco.net/about_us/committees_and_groups/scrum/ibcao/documents/ibcaoposter.pdf for inspiration)
    * ridges
    * abyssal plains
    * etc.
   
But maybe this will be too *geologically focused*. Geologists could always create their own collection and share them will like-minded.

**Comment by Esteban82** [comment]
> I try it but without any luck. Maybe it wasn't implement yet? Pinging @PaulWessel.

I managed to do it. So, returning to your questions, you can add your local codes in `.gmt/dcw-collections.txt`. It works as expected.

**Comment by anbj** [comment]
Brilliant - thanks Estban!

**Comment by Esteban82** [comment]
> In one way, not really. You've done a brilliant job, and this will be super useful to many users, including me.
> 
> That said (as a geologist), one could imagine also including entries for
> 
>     * tectonic plates
> 
>     * oceanic features such as (see e.g. https://www.gebco.net/about_us/committees_and_groups/scrum/ibcao/documents/ibcaoposter.pdf for inspiration)
>       
>       * ridges
>       * abyssal plains
>       * etc.
> 
> 
> But maybe this will be too _geologically focused_. Geologists could always create their own collection and share them will like-minded. And I don't know if there exists a document(s) that can be used for reference/anchors for these names, like you have used for e.g. the oceans.

I am also geologist. The tectonic plates are too specific. The oceanic features can be a good idea.

**Comment by PaulWessel** [comment]
The user-controlled DCW file is called ./gmt/dcw.conf, not dcw-collections.txt (the latter is the file shipped with DCW).

**Comment by anbj** [comment]
I see. Thanks Paul.

**Comment by anbj** [comment]
Does it make sense to allow ``-R[..]r`` in *dcw.conf*?

**Comment by anbj** [comment]
Maybe *SCUFN* (GEBCO SUB-COMMITTEE ON UNDERSEA FEATURE NAMES) which contains a lot of names; https://www.gebco.net/data_and_products/undersea_feature_names/.

**Comment by PaulWessel** [comment]
I am hesitant to add hundred of names to the collections since it becomes hard to find things.  But I am not opposed, just hesitant.

As for -R...+r: should be harmless but the region depends on the projection and that is usually not what you want.

**Comment by anbj** [comment]
Yes, it’s probably a bit too much.

**Comment by Esteban82** [comment]
Yes, maybe there are too many, but we can think on creating like categories of regions (seas, islands, lakes) to facilitate the users. And, because of this I want also to provide the pdf with the maps of each record. 

BTW, I also have thought to include features represented with points (like cities, mountains, etc). It will require some extra coding since it is only long and latitude. This could wait.

**Comment by anbj** [comment]
The *digital gazetteer* of scufn is really comprehensive. I think it's thousands of entries. Really nice discovery in general; it's relatively easy to extract feature names that you can use to put lablels on your map.

I also thought about how one should deal with points - one way is to simply make a suitable buffer around the point (which turns it into a polygon, and then create an envelope. Then you get a rectangle that `-R` is happy to eat. This would make further coding unnecessary.

**Comment by Esteban82** [comment]
> The user-controlled DCW file is called ./gmt/dcw.conf, not dcw-collections.txt (the latter is the file shipped with DCW).

Is it possible to ship an empty version of the `./gmt/dcw.conf.txt` file (with maybe some comments for the users)? I think that it will help the users.

**Comment by PaulWessel** [comment]
Perhaps #6249 is enough?

**Comment by Esteban82** [comment]
Yes, I think is enough.

**Pull request merged**
