### PR TITLE
Update server files to remove extra whitespaces

### PR DESCRIPTION
**Pull request by Esteban82**
See #38.

I update the AF files. Please let me know if I make the PR ok (it is the first time I am doing it from VSC).

### CODE REVIEW

**Comment by Esteban82** [comment]
I use this command to remove the extra whitespaces:
`sed -i "s/^ *//;s/ *$//;s/ \{1,\}/ /g" *.txt`

And this to reduce the decimals to 6 values
`gmt convert old.txt -fg  --IO_COL_SEPARATOR=space --FORMAT_FLOAT_OUT=%.6lf > new.txt`

The later was only applied to: BV, ER, ET, SD, SS, TF.

**Review by PaulWessel — APPROVED** [review]
Thanks, looks fine.

**Review by PaulWessel — APPROVED** [review]

**Comment by Esteban82** [comment]
I see that there is a conflict. It seems my local branch don't have the latest changes. 

For the RU.txt and CHU.txt files I manually updated. The same for the DE.txt and NL.txt (in Europe). 

Not sure how should I proceed.

**Review by PaulWessel — APPROVED** [review]
I am basically approving these blind since it is too much work to build the netcdf and a new version and test it...

**Comment by Esteban82** [comment]
I finished updating all the files. For the 5 files that have conflicts (RU, CHU, DE, NL, FJ) I carefully modify them considering the last changes.

**Comment by Esteban82** [comment]
@PaulWessel maybe now you could create the netcdf to test it.

**Comment by PaulWessel** [comment]
Will try tomorrow Thursday.

**Comment by Esteban82** [comment]
> Will try tomorrow Thursday.

Ok. This is the checksum of the tar.gz file: `42c6ee7529a3556b315646fb14cbf463`.

And this the figure that I get:

dcw-figure

**Comment by PaulWessel** [comment]
Looks like you either did not update master before you started on this branch? The config.mk file says 2.0.1, for instance while master says 2.0.2.
I think if you are sure those 5 files are correct then look at how to merge while forcing the new files to be taken as is.  Maybe either @meghanrjones or @seisman can advice on git stuff - I am just a git abuser.

**Review by PaulWessel — APPROVED** [review]

**Comment by meghanrjones** [comment]
There's two options given the size of the changes:
1. Merge the master branch into Reformat-orig-files using the versions of RU.txt, CHU.txt, DE.txt, NL.txt, and FJ.txt that are in Reformat-orig-files (this assumes that all changes from the master branch have been made independently here).
2. Merge the master branch into Reformat-orig-files using the versions of RU.txt, CHU.txt, DE.txt, NL.txt, and FJ.txt that are in the master branch and then re-run the formatting steps on those five files.

Would you want me to take one of those actions to resolve the merge conflicts, @Esteban82?

**Comment by Esteban82** [comment]
Let's do 2) to be completely sure.

**Comment by meghanrjones** [comment]
OK, I merged in master accepting all incoming changes. You'll need to do a `git pull` before reformatting the 5 files that had merge conflicts.

**Comment by Esteban82** [comment]
I think that everything is ready now.

**Comment by Esteban82** [comment]
Should we write something in the changelog?

**Comment by PaulWessel** [comment]
You could add an entry like "Reformat original files using consistent format and white-space" so that in the future we at least will remember this happened should something odd show up later

**Comment by PaulWessel** [comment]
So do that, and then you can merge since already approved.

**Pull request merged**
