### PR TITLE
Add counties of mainland Norway (NO)

### LINKED ISSUE #88: Add states for Norway
I know, you've said it many times; don't spend time on dcw. But, I want ot scratch my own itch, and it's fun to learn the plumbing of dcw. So I would like to add the 'states' (counties) of Norway. Some questions;

* do the county lines have to be closed? I've looked at *DCW2singleshortnc.sh* and based on that, my guess is they do.
* the lines/polygons extend ~12 nautical miles off the coast ('territorial limit'). Is that ok? Or do they have to be clipped to the country polygon?
* Any place to document source and year the data is from?

### PR DESCRIPTION
**Pull request by anbj**
Should close #88.

### CODE REVIEW

**Comment by anbj** [comment]
Preview:

`$ gmt pscoast -Bafg -ENO.03+gblack -ENO.11+gorange -ENO.15+ggray -ENO.18+ggold -ENO.30+ggreen -ENO.34+gcyan -ENO.38+gred -ENO.42+ggreen -ENO.46+gblue -ENO.50+glightgreen -ENO.54+glightblue -pdf test -JM15c -RNO`
NO

**Comment by PaulWessel** [comment]
Nice, but as someone from Sarpsborg I want my Østfold back. Viken sucks.

**Comment by anbj** [comment]
You have my sympathy. I'm just glad they didn't touch Rogaland.

**Comment by Esteban82** [comment]
> `$ gmt pscoast -Baf -ENO.03+gblack -ENO.11+gorange -ENO.15+ggray -ENO.18+ggold -ENO.30+ggreen -ENO.34+gcyan -ENO.38+gred -ENO.42+ggreen -ENO.46+gblue -ENO.50+glightgreen -ENO.54+glightblue -png NO -JM15c -RNO+r1 -ENO`

I test it and I got the same result. 

Just reduced the decimals to 6 and I will approve it.

**Comment by PaulWessel** [comment]
If @anbj is using GMT then adding --FORMAT_FLOAT_OUT=%.6lf will do it

**Comment by PaulWessel** [comment]
True, but just sticking with established scheme for now instead of making exceptions.

**Comment by Esteban82** [comment]
Sorry, I found the error. My mistake.

**Review by Esteban82 — APPROVED** [review]

**Comment by Esteban82** [comment]
I got this figure for the readme file. I don't know how to updated (and if we have to wait for the dcw 2.2.0 released to update it).

dcw-figure

**Comment by anbj** [comment]
> Nice, but as someone from Sarpsborg I want my Østfold back. Viken sucks.

Østfold is back. Congratulations!

**Comment by PaulWessel** [comment]
Thanks! But still stuck living in Viken (Nittedal).

**Comment by anbj** [comment]
Hope Akershus is better Viken?

**Pull request merged**
