### PR TITLE
Add dcw-collection.txt

### PR DESCRIPTION
**Pull request by Esteban82**
List of sub-regions of countries from UN49.
https://en.wikipedia.org/wiki/UN_M49

### CODE REVIEW

**Comment by Esteban82** [comment]
A map of the regions of Africa

`gmt coast -Bf -Ggray -png map -N1 -R=AF -JM15c -EUN015+gred -EUN014+gorange -EUN017+gyellow -EUN018+ggreen -E"Western Africa"+gblue`


map

**Review by PaulWessel — COMMENTED** [review]
Nice! Please make two changes:

1. Add the URL to the wikipedia description of the geoscheme in the header section.
2. Add list: in from of all the lists of codes.

**Comment by Esteban82** [comment]
Ok. About 2) you mean I should modified each list like this, right?

**list:** DZ,EG,LY,MA,SD,TN,EH

**Comment by joa-quim** [comment]
Hmm, not related to this but the **-RAF** area extends too much to South (Kergelen should not be included) a to the East where it should stop a bit east of Madgascar.

**Comment by Esteban82** [comment]
> Hmm, not related to this but the **-RAF** area extends too much to South (Kergelen should not be included) a to the East where it should stop a bit east of Madgascar.

I agree. For this, we should remove AF of some countries/territories from dcw-countries.txt. In the other continents there are similar cases. 


Asia

**Comment by PaulWessel** [comment]
Maybe similar to what we had to do to Norway - strip off that Spitsbergen outlier.

**Comment by Esteban82** [comment]
I think that the main issue is that we are defining the continent (=AF, =AS, =EU, etc) as a collection of countries and not geographically. And sometimes this include small islands far away from the shore or exclave (like Kaliningrad). Which is similar of what we are doing with UN M49.

**Comment by PaulWessel** [comment]
No longer case-sensitive.  Also, fixed issue so that parsing error in these files leads to an error and exit.

**Comment by PaulWessel** [comment]
Two questions:

1. Regarding the regions of the continents: WIth collections we could add our continents that way instead, via AF, EU entries in dcw-collections.txt.  The source code can handle any backwards compatibilities like =AF to be come AF or Africa.  Are there official regions we can use instead of the named collections of countries? This will requires both 6.4.x and 2.0.2 for users to notice.
2. The file looks good and with IHO28-1 or -2 there are no case issues that I can see, meaning the current case-insensitive coding can stand, yes?

**Comment by PaulWessel** [comment]
I fixed the Arctic Ocean which had a strange w/e (not quite 360) and north exceeded 90.
In fact, I see lots of coordinates that have noise, e.g. Indian Ocean:

`region: 20.000000000000057/146.836278/-70.4284/10.437097927000082`

the difference between 20.000000000000057 and 20 are a few nanometers...  Surely none of these borders are more accurate than a meter, meaning we should probably truncated to 6 decimals? 1e-6 * 111113 m = 11 cm.

**Comment by Esteban82** [comment]
> The file looks good and with IHO28-1 or -2 there are no case issues that I can see, meaning the current case-insensitive coding can stand, yes?

Yes, I took them from the shp file. It is NOT the official tag (of IHO53) but I think we can use them to avoid case-sensitive issues.

**Comment by Esteban82** [comment]
> Regarding the regions of the continents: WIth collections we could add our continents that way instead, via AF, EU entries in dcw-collections.txt. The source code can handle any backwards compatibilities like =AF to be come AF or Africa. 

Do you mean to add the continents in the list? Yes, it is possible. They have an official number like the sub-regions. It would something like:
```

# Africa
tag: UN002 Africa
list: all the iso codes of Africa
```

It would be possible to call the other sub-regions? like:
`list: UN015, UN014, UN017, UN014, UN011 `


> Are there official regions we can use instead of the named collections of countries? This will requires both 6.4.x and 2.0.2 for users to notice.

I am not sure if understand correctly. Do you other regions define by another organism? Or by the UN?

**Comment by Esteban82** [comment]
> . Surely none of these borders are more accurate than a meter, meaning we should probably truncated to 6 decimals? 1e-6 * 111113 m = 11 cm.

From the paper of Fourcy and Lorvelec: "Positioning precision of reference points is approximately 10 s of meridian arc (about 300 m)."

**Comment by PaulWessel** [comment]
> > Are there official regions we can use instead of the named collections of countries? This will requires both 6.4.x and 2.0.2 for users to notice.
> 
> I am not sure if understand correctly. Do you other regions define by another organism? Or by the UN?

Sorry, I meant can we find official w/e/s/n regions for all continents and then we use that for AF etc instead of a list of countries, since that includes Kerguelen and other troubles.

**Comment by PaulWessel** [comment]
OK, so on resolution I think reformat to %.6lg to avoid those long we/s/n/ strings

**Comment by Esteban82** [comment]
> Sorry, I meant can we find official w/e/s/n regions for all continents and then we use that for AF etc instead of a list of countries, since that includes Kerguelen and other troubles.

Do you mean to have the limits of the continents based of the geology (so excluding all the island that are included in a continent). And the problem would be for example how to differentiate the geological Africa from the geopolitical Africa, right? 

I think I could get the w/e/s/n for the geological continents (which can't be based on countries due to the issue with islands and intercontinental countries like Russia).

**Review by PaulWessel — APPROVED** [review]

**Comment by Esteban82** [comment]
> 1. The source code can handle any backwards compatibilities like =AF to be come AF or Africa.

Here you idea is to remove the continents of the DCW?

Because I am seeing the continents defined by the UN is different from the DCW. For example Russia is in Europe, Greenland in America. So `-R=EU` is different than `-RUN150`. Should we re-arranged the countries in DCW?

**Comment by PaulWessel** [comment]
I think we should follow the UN - that should be more reputable than whatever DCW did.  I cannot recall exactly how I did things initially but I am the one who assigned countries to continents (I think) so that could be wrong.

**Comment by Esteban82** [comment]
> I think we should follow the UN - that should be more reputable than whatever DCW did. I cannot recall exactly how I did things initially but I am the one who assigned countries to continents (I think) so that could be wrong.

Ok. So I should reorganize the countries in the dcw folders, right?

**Comment by PaulWessel** [comment]
Yes, if you have time.  I need to do some errands this morning so will be back in a few hours.

**Comment by Esteban82** [comment]
About the list and regions of dcw-collection in general. 

I think that it would be good to have like smaller collections (like Balcans, Scandinavian or Greater and Less Antilles) but I didn't find any official list (like UN). So maybe we can leave that additions for a second version of this list. What do you think?

**Comment by Esteban82** [comment]
> Yes, if you have time. I need to do some errands this morning so will be back in a few hours.

Ok, I will do it tonight (UTC -3).

**Comment by Esteban82** [comment]
Here is how the UN regions would be. I already add Kosovo to Europe. I still have to change some countries. 

My doubt is about the Americas. Should I use set =NA with North America (meaning US, CA, Greenland, Saint Pierre and Miquelon and Bermuda) and =SA to Latin America and the Caribbean. So we will reverting some changes made for dcw 
2.0.1 but I think that we have to do it.


UN

**Comment by PaulWessel** [comment]
I see, so the UN conventions differ from the Wikipedia pages we used for 2.0.1 then? Pretty odd.  But the good news is that I do not think anyone would really be affected if we make the change.  I am happy with your decision on this.

**Comment by Esteban82** [comment]
Ok. 

I am not sure how to make a new release. Can we make a checklist to do it?

**Comment by Esteban82** [comment]
Is this [checklist](https://github.com/GenericMappingTools/dcw-gmt/blob/master/.github/ISSUE_TEMPLATE/release_checklist.md), right?

**Comment by meghanrjones** [comment]
> Is this [checklist](https://github.com/GenericMappingTools/dcw-gmt/blob/master/.github/ISSUE_TEMPLATE/release_checklist.md), right?

Yes, if you click 'New issue' from the [issues page](https://github.com/GenericMappingTools/dcw-gmt/issues) in the dcw repository, you can create a release checklist by clicking 'Get started' next to the 'dcw release checklist' option.

**Comment by Esteban82** [comment]
> I see, so the UN conventions differ from the Wikipedia pages we used for 2.0.1 then?

I never follow the Wikipedia (or any official list) to see the continents.

I think that the best would be to clarify in the docs that =SA is Latin American and the Caribbean. And that the continents (=AF,=AS,=EU, etc) follow the UN definition of M49.

**Comment by PaulWessel** [comment]
I mean, when we changed what Caribbean countries below to we did look at Wikipedia lists and learned they belong to NA, no?
Anyway, I agree we should follow UN definition.

**Comment by joa-quim** [comment]
> I think that the best would be to clarify in the docs that =SA is Latin American and the Caribbean.

But Caribbean is not part of South America. Regardless of whatever some UN definition may say (IF it says it)

**Comment by PaulWessel** [comment]
OK, we should determine why UH says Caribbean is part of South America and Greenland is part of North America.  I Agee with @joa-quim that this does not seem right and it is a pretty bit difference.  If I were a greenlander I probably would bristle if someone called me a North American, no?

**Comment by joa-quim** [comment]
Ofc. Everybody knows that greenlanders are not red-skin.

**Comment by Esteban82** [comment]
The UN says that there are 4 regions in the Americas
1. North America
2. Central America
3. Caribbean
4. South America

The last 3 are part of a larger group: Latin America and the Caribbean. 

The issue is if we want to have a compatibility between the codes =SA and =NA and the UN codes. If we don't then there is no issue.

**Comment by PaulWessel** [comment]
Thanks for checking, @Esteban82.  So it is basically a difference between "continents" (which we have defined before and Greenland is in Europe etc) and UH "regions" which can be whatever the UH decides.  So yes, the answer is we do not want compatibility since it is not strictly the same thing.  I think users of NA would be surprised to see Greenland whereas users of that UH region would expecting.  So this is all good I think and resolves our issue.

**Comment by joa-quim** [comment]
Doesn't that mean we need a =CA and eventually a =CB?

**Comment by PaulWessel** [comment]
I think not.  These are already named in the UN collections that will come with DCW 2.1.0.

**Comment by PaulWessel** [comment]
To be clear, the old =AF etc might even be retired - we now allow -RAfrica instead for instance (We will allow =AF of course but it may no longer be documented).  The Dow_collections.txt file will have named continents and regions etc for all to use.

**Comment by Esteban82** [comment]
Ok. So we shouldn't spend any more time on the DCW continents (=SA,=NA,=EU, etc).

**Comment by PaulWessel** [comment]
yes, I think not.  Sorry for going a bit in circles on this but I did not realize what the UN did on this.

**Comment by Esteban82** [comment]
PDF with the UN regions.
[Regiones.pdf](https://github.com/GenericMappingTools/dcw-gmt/files/7681941/Regiones.pdf)

 
I think I will add some smaller regions probably based on Wikipedia.

**Comment by PaulWessel** [comment]
Nice, looks like a **gmt batch** job!

**Comment by Esteban82** [comment]
Exactly. 

By the way, Is there any way to get the list of regions/seas to use as input of `gmt batch`? I mean, I can do  `gmt coast -E=EU+l > countries.txt` to get a list of codes and countries names. Is it possible to do the same for the future regions and seas of dcw-collections.txt?
```

UN002	Africa
UN005	South America
UN009	Oceania
UN010	Antarctica
UN011	Western Africa
UN013	Central America
UN014	Eastern Africa
UN015	Northern Africa
,,,
```

**Comment by PaulWessel** [comment]
We can make that happen.  You see the +n was added to list collections, and if you give a country code it will only list collections containing that country.  See what you need and make a feature request.  Ideally it would not matter if it is UN or the other sets of things but perhaps you will need to choice.

**Comment by joa-quim** [comment]
Do we really want to have a region called "Europe" that goes from the Azores to the Bering Strait, and another that insists in punting Greenland in America?

I don't care what UN says, users will blame us for that not the UN.

**Comment by Esteban82** [comment]
Yes, I agree about Europe. But there is no easy way to separate the countries (and territories as defined by the isocodes) in continents because there are intercontinental countries (like Russia) and islands far way from the coast.
So, when we deal with list of countries we always will have this problem. 

About the UN, maybe we could add a prefix (UN?) to the full name. So the user can use it this way and define "Europe" based on a region (W/E/S/N). 

We can't make a **list** for Europe because of Russia and the Azores and the Canary islands that are include in the polygon of Portugal and Spain. 

`gmt coast -R"UN Europe" -E"UN Europe"+gred -Bag -JQ10c -png Europe -W -Ggray`

Europe

**Comment by Esteban82** [comment]
Here ([UN_Regions.pdf](https://github.com/GenericMappingTools/dcw-gmt/files/7686162/UN_Regions.pdf)) I add the UN prefix to the long name. Now the names of the continents are free to redefine.

**Comment by PaulWessel** [comment]
@Esteban82, I have merged in master to this branch so it should be up-to-date with respect to master.

**Comment by Esteban82** [comment]
> @Esteban82, I have merged in master to this branch so it should be up-to-date with respect to master.

Great, thanks.

**Comment by Esteban82** [comment]
In [Natural Earth Data](https://www.naturalearthdata.com/downloads/110m-physical-vectors/110m-physical-labels/) there is a shp file that contains [physical regions](https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/physical/ne_110m_geography_regions_polys.zip).  I think we can extract the bounding box region. In the 1:110m scale version of the file there are 63 in total (but many correspond to island/countries like Australia, Iceland). In the 1:50m there are 579 (maybe too many to begin).

I think we could add the regions of the 1:110. What do you think?
I check and I think that you will be happy with the definition of the continents.

**Comment by Esteban82** [comment]
I made [these maps](https://github.com/GenericMappingTools/dcw-gmt/files/7762961/Geography.pdf) from the geographic regions of the Natural Earth (scale 1:110). I think it is good. What do you think??

I just would need to adjust some values and see some issues with -180. Also the codes should be revised. 

BTW I got help from a colleague (@sebaprincip) to extract the bounding box regions from the shp files.

**Comment by meghanrjones** [comment]
Some are great, but I am confused about others (e.g., NAM, ASI). Why do these span -180 to 180 longitude?

**Comment by Esteban82** [comment]
> Why do these span -180 to 180 longitude?

The script used just take the original info from the shp. And in the file, the polygon are split in along the 180 meridian. In NAM it includes de Aleutian islands.

**Comment by PaulWessel** [comment]
OK, so the Asia one will go from whatever the westernmost positive longitude is (middle east somewhere) and exceed 180, eg 191 of whatever.  That is fine in GMT.

Same with NA.  It needs -190 or what the most west point is to -60 or the east point.

Same with Melanesia, Polynesia and I guess anything that crossed the Dateline.  GIS are dumb things...

**Comment by Esteban82** [comment]
Yes, I have just to fix those issues. 

For Micro/Mela/Polynesia I also have to compare with the UN definition.

**Comment by joa-quim** [comment]
I think the bounding boxes are a bit too tight. See Africa, Europe (trims a bit of Ireland), Iberia (shaves the westernmost points). Maybe add a little pad to all of them? But that pad must probably proportional to width/height.

**Comment by Esteban82** [comment]
> I think the bounding boxes are a bit too tight. See Africa, Europe (trims a bit of Ireland), Iberia (shaves the westernmost points). 

Yes, I meant this when I said "adjust some values". 

> Maybe add a little pad to all of them? But that pad must probably proportional to width/height.

Do you mean an extra space between the shore and the bounding box?

**Comment by Esteban82** [comment]
> Europe (trims a bit of Ireland)

I checked the shp. Europe = Continental Europa so that is why Ireland is trim. It is part of British Isles. Should we include them in Europe, right?

> Iberia (shaves the westernmost points).

Which are they? The Berlengas Islands?

**Comment by joa-quim** [comment]
> I checked the shp. Europe = Continental Europa so that is why Ireland is trim. It is part of British Isles. Should we include them in Europe, right?

Abasolutely.

> Which are they? The Berlengas Islands?

It's the westernmost tip of Europe. "Cabo da Roca". But the "Andes" is even worst.

image

**Comment by Esteban82** [comment]
Thanks Joaquim. I will keep in mind.

Another issue. I will add the info of major lakes. I can use directly the GSHHG level 2. I noticed that the bounding box is included in the header so would be easy. Maybe in the future we could add the tag directly on it? What do you think?

> Id = 763 N = 46 G = 0 L = 2 E = 180 S = 0 R = 46.679720/54.766110/36.580000/47.115280 A = 397052.350619 B = 403040.418798 P = 0 F = 180506

**Comment by PaulWessel** [comment]
I thin maybe it is OK to add a name at the end of those records but would need to check to code in src that it does not break anything.

**Comment by Esteban82** [comment]
> I will add the info of major lakes. I can use directly the GSHHG level 2.

I have a doubt. What GSHHG resolution should I use to extract the bounding box? I was thinking `full` but I am not sure.

**Comment by Esteban82** [comment]
I add the 14 major lakes (by area) plus the Great Lakes from [wikipedia](https://en.wikipedia.org/wiki/List_of_lakes_by_area). 
[Lakes.pdf](https://github.com/GenericMappingTools/dcw-gmt/files/7790193/Lakes.pdf)


Also add the biggest islands (greater than 25,000 km2) also from [wikipedia]. (https://en.wikipedia.org/wiki/List_of_islands_by_area). I do not include islands that can be drawn trough DCW (Iceland, Cuba, Madagascar, Hispaniola, Tasmania, etc). 
[Islas.pdf](https://github.com/GenericMappingTools/dcw-gmt/files/7790192/Islas.pdf)

I also want to add some main archipelagos (Canary, Madeira, Galapagos, etc). I here suggestions to add. 

I get the shoreline from the full version of GSHHG level 2 (and 6 for two antarctic islands) so it shouldn't be any problem with the bounding box (but please check).

**Comment by Esteban82** [comment]
> I noticed that the bounding box is included in the header so would be easy. Maybe in the future we could add the tag directly on it? What do you think?
> 
> > Id = 763 N = 46 G = 0 L = 2 E = 180 S = 0 R = 46.679720/54.766110/36.580000/47.115280 A = 397052.350619 B = 403040.418798 P = 0 F = 180506

I think we could even call the entire island from here. To be clear, if I want to get the coastline of Siciliy, I could write something like `gmt coast -LetterSicily -M -W > Sicily.txt" and GMT would extract only the coastline of the the polygon called Sicily. So we would have to add a name (and a code) in the headers, and @PaulWessel would have to write some code to search for the name (or code).

**Comment by PaulWessel** [comment]
> I have a doubt. What GSHHG resolution should I use to extract the bounding box? I was thinking `full` but I am not sure.

All the resolutions file has the same bounding box (full) for each feature. However, lower resolution will have fewer features.  I think the large things you are considering should be in all, with the possible exception of crude.

**Comment by Esteban82** [comment]
> All the resolutions file has the same bounding box (full) for each feature. However, lower resolution will have fewer features. I think the large things you are considering should be in all, with the possible exception of crude.

Ok. I also use full resolution because that was used to define the limits of the sea regions.

**Comment by Esteban82** [comment]
> I think we could add the regions of the 1:110. What do you think?

I fix the geographic regions and make topographic grid from the gebco grid. 
[Geography_relief.pdf](https://github.com/GenericMappingTools/dcw-gmt/files/7804180/Geography_relief.pdf)

What do you think? For some regions, maybe the values can be adjust a bit more but I think that it is too much work for a very little detail. So I am thinking of leave these regions as they are. Although if you want to fix some particular region, I could do it (let me know).

Remember that this is just a sub-set of the regions. Others are lists of countries (from UN and others), regions of seas/oceans, major lakes, biggest islands and some main archipelagos.

**Comment by joa-quim** [comment]
I have this Julia function that should be pretty useful for this.

A made up example
```
julia> GMT.round_wesn([-1.111 5.567743 -6.976346 9.98658])
1×4 Matrix{Float64}:
 -1.2  5.6  -7.2  10.0
```

**Comment by Esteban82** [comment]
> I have this Julia function that should be pretty useful for this.

Thanks. Looks fine but the main issue is that the geographic regions of the shp are based in another coastline (not GSHHG) and the error it can be 0.0x degress. So I would need to revise them manually (which is too much).

**Comment by Esteban82** [comment]
I upload the collections to revise in 3 files. The first 2 are based on bounding box regions, the 3rd is a list of countries. In all of them I include the long name (title) and code (label). For the codes I used mostly 4 letters.  

1. [Geography_relief.pdf](https://github.com/GenericMappingTools/dcw-gmt/files/7826516/Geography_relief.pdf): 37 geographic regions based on Natural Earth 1:110.
2. [Seas.pdf](https://github.com/GenericMappingTools/dcw-gmt/files/7826524/Seas.pdf): 161 seas, lakes, islands and archipelagos. The seas are based on IHO53. I include 2 more seas (Sargasso and Southern Ocean). Also include lakes, major islands and archipelagos from the GSHHG (full resolution file). I do not include islands that can be drawn with DCW (Cuba, Hispaniola, Cabo Verde, etc.). 
3. [Regiones.pdf](https://github.com/GenericMappingTools/dcw-gmt/files/7826536/Regiones.pdf): 46 collections (or lists) of countries. 30 are from the UN49 and the rest I took them from Wikipedia. Maybe some more could be add (let me know, it is very simple).

In total there are 244 regions. Maybe we could go up to 250?

**Comment by PaulWessel** [comment]
Very nice work, @Esteban82!  I think 244 is quite a few already and we can always add more later.

**Comment by Esteban82** [comment]
Ok, thanks @PaulWessel.

So please revised so we can merge it.

**Review by PaulWessel — APPROVED** [review]

**Comment by Esteban82** [comment]
> I upload the collections to revise in 3 files. The first 2 are based on bounding box regions, the 3rd is a list of countries. In all of them I include the long name (title) and code (label). For the codes I used mostly 4 letters.
> 
>     1. [Geography_relief.pdf](https://github.com/GenericMappingTools/dcw-gmt/files/7826516/Geography_relief.pdf): 37 geographic regions based on Natural Earth 1:110.
> 
>     2. [Seas.pdf](https://github.com/GenericMappingTools/dcw-gmt/files/7826524/Seas.pdf): 161 seas, lakes, islands and archipelagos. The seas are based on IHO53. I include 2 more seas (Sargasso and Southern Ocean). Also include lakes, major islands and archipelagos from the GSHHG (full resolution file). I do not include islands that can be drawn with DCW (Cuba, Hispaniola, Cabo Verde, etc.).
> 
>     3. [Regiones.pdf](https://github.com/GenericMappingTools/dcw-gmt/files/7826536/Regiones.pdf): 46 collections (or lists) of countries. 30 are from the UN49 and the rest I took them from Wikipedia. Maybe some more could be add (let me know, it is very simple).
> 
> 
> In total there are 244 regions. Maybe we could go up to 250?

I just wonder if these pdf should be available for the user to sea more easily the lists and regions.

**Comment by PaulWessel** [comment]
I am not sure where they could go.  However, maybe those **batch** scripts could be added as examples for how users can visualize all things. Or maybe @meghanrjones has a better idea.

**Comment by meghanrjones** [comment]
I like the idea of sharing example scripts along with the figures. Are the batch scripts posted anywhere?

**Comment by Esteban82** [comment]
I will share them soon.

**Comment by Esteban82** [comment]
I share a zip file which has 3 files and its  respective lists. 
[Scripts.zip](https://github.com/GenericMappingTools/dcw-gmt/files/7891573/Scripts.zip)

**Pull request merged**
