### PR TITLE
Remove MO and HK from UN lists

### LINKED ISSUE #93: Latest DCW lost Monaco and Hong Kong
pscoast -EUN142
pscoast [WARNING]: No country code matching HK (skipped)
pscoast [WARNING]: No country code matching MO (skipped)
-R25.66851/145.820877/-11.007615/55.431812

pscoast -EUN030
pscoast [WARNING]: No country code matching HK (skipped)
pscoast [WARNING]: No country code matching MO (skipped)
-R73.557701/145.820877/15.78/53.56086

pscoast -EHK
pscoast [WARNING]: No country code matching HK (skipped)
pscoast [WARNING]: Column selected for latitude-formatting has values that exceed +/- 90; set to NaN
pscoast [WARNING]: Column selected for latitude-formatting has values that exceed +/- 90; set to NaN
-R0/0/NaN/NaN

### PR DESCRIPTION
**Pull request by Esteban82**
In #73 MO and HK were deleted as separated countries. Now I remove the codes from the DCW-Collections.

An alternative way would be to add the codes of China (CN.MO and CN.HK) but I think that it doesn't make sense.

Fixes #93.

### CODE REVIEW

**Comment by Esteban82** [comment]
I think that this PR should fix the issue but I don't remember exactly how to test it.
Should we make a new release? Version 2.2.0?

**Comment by joa-quim** [comment]
Removing them from the list collection is not the point- The point is why did they disappear from the netcdf file.

**Comment by Esteban82** [comment]
That was discussed in #55. There it was suggested that:

> For HK and MO the solution is clear: Neither are separate entities since the late 1990s and only CN.HK and CN.MO should exist (the database predates all of the 1997/99 changes).

So, these two codes were remove as countries in #56. 

If you want to use them, then use `CN.HK` and `CN.MO`.

**Comment by Esteban82** [comment]
Maybe a better solution is to add the CN.HK and CN.MO instead in the dcw-collections. The UN list, as defined by them, includes also special territories.

**Comment by Esteban82** [comment]
> I would not have agreed with that if I had payed more attention, as I don't agree that we have moved `TW` into `CH.TW`. We all now that this a political matter where we don't want to get involved, but with that move we just did.

Yes, I agree. But we didn't move Taiwan. You should be able to use both (`TW `and `CN.TW`). I have deleted TW but only by mistake. It was already fix (#73). 

We only remove Macao and Hong Kong as countries (MO and HK).

**Comment by joa-quim** [comment]
Sorry, I start to be confused with this. What we should have is both: ``CH.HK, CH.MO, CH.TW`` **and** ``HK, MO, TW`` (HK & MO are little polygons, no problems with duplications)

**Pull request closed without merging**
