### PR TITLE
Add new RU

### PR DESCRIPTION
**Pull request by Esteban82**
See #40.

Is it possible that I directly deleted the previous Version? Sorry.

### CODE REVIEW

**Comment by Esteban82** [comment]
In this file the values are from 0-360 (in the previous one I use `--FORMAT_GEO_OUT=-D` instead of `+D`). And 2 polygon were join (so there are 2 segments less).

**Review by PaulWessel — APPROVED** [review]

**Comment by Esteban82** [comment]
Ok. Later I will try to fix Chukotka and Fiji.

**Comment by Esteban82** [comment]
I have no much time to fix Chukotka and Fiji. So maybe we squash and merge this PR, to make the release 2.0.2 (#39).

**Comment by PaulWessel** [comment]
Maybe I can have a look.  Are these split into two at the Dateline or something?

**Comment by PaulWessel** [comment]
The CHU has been fixed in this PR.  However, the FJ problem seems to be that all the pieces to the east of the dateline are not in the data set.  So we will need to find these pieces from other data...

**Comment by Esteban82** [comment]
Are you sure? From the previous map It seems that there is data.  just saw that the data is in -180/180.

**Comment by PaulWessel** [comment]
Will check again after major old Mac to new Mac migration…

**Comment by PaulWessel** [comment]
Indeed, just forgot a -fg in my dumb plot script.

**Comment by PaulWessel** [comment]
I think I got Fiji fixed; please check.

**Comment by Esteban82** [comment]
Ok I will check now.

**Comment by Esteban82** [comment]
Chukotka is Ok. 

Fiji I think not. I got this figure:

`gmt plot FJ.txt -Wred -Gblue -fg -Baf -png Fiji -R179.8/180.2/-17.02/-16.45 -JQ10c`


Fiji

**Comment by PaulWessel** [comment]
Thanks, yes there were odd extra points and I must have left one or two in...

**Comment by PaulWessel** [comment]
Better now I hope.

**Comment by Esteban82** [comment]
Yes, now it is ok.

Fiji

So, I should update changelog and squash and merge, right?

**Review by PaulWessel — APPROVED** [review]

**Comment by Esteban82** [comment]
Closes #40 .

**Pull request merged**
